---
# Helm deployment
helm_enabled: true
helm_version: v3.14.3
helm_repositories:
  prometheus-community: https://prometheus-community.github.io/helm-charts
  traefik: https://traefik.github.io/charts
  argocd: https://argoproj.github.io/argo-helm
  bjw-s: https://bjw-s.github.io/helm-charts/
  cnpg: https://cloudnative-pg.github.io/charts
  bitnami: https://charts.bitnami.com/bitnami
  jetstack: https://charts.jetstack.io
  ingress-nginx: https://kubernetes.github.io/ingress-nginx
  rook: https://charts.rook.io/release
  metallb: https://metallb.github.io/metallb
  nextcloud: https://nextcloud.github.io/helm/
  hashicorp: https://helm.releases.hashicorp.com
  immich: https://immich-app.github.io/immich-charts
  bootc: https://charts.boo.tc
  jameswynn: http://jameswynn.github.io/helm-charts
  external-dns: https://kubernetes-sigs.github.io/external-dns/
  emberstack: https://emberstack.github.io/helm-charts
  kubeshark: https://helm.kubeshark.co
  oauth2-proxy: https://oauth2-proxy.github.io/manifests
  stakater: https://stakater.github.io/stakater-charts
  nfd: https://kubernetes-sigs.github.io/node-feature-discovery/charts
  intel: https://intel.github.io/helm-charts/
  blakeblackshear: https://blakeblackshear.github.io/blakeshome-charts/


# Registry deployment
registry_enabled: false
registry_version: 2.8.1
# registry_namespace: kube-system
# registry_storage_class: ""
# registry_disk_size: "10Gi"

# Cert manager deployment
cert_manager_enabled: true
cert_manager_version: v1.13.3
cert_manager_namespace: cert-manager
# cert_manager_tolerations:
#   - key: node-role.kubernetes.io/master
#     effect: NoSchedule
#   - key: node-role.kubernetes.io/control-plane
#     effect: NoSchedule
# cert_manager_affinity:
#  nodeAffinity:
#    preferredDuringSchedulingIgnoredDuringExecution:
#    - weight: 100
#      preference:
#        matchExpressions:
#        - key: node-role.kubernetes.io/control-plane
#          operator: In
#          values:
#          - ""
# cert_manager_nodeselector:
#   kubernetes.io/os: "linux"

# ArgoCD GitOps
argocd_enabled: true
argocd_version: v2.12.0
# Default password:
#   - https://argo-cd.readthedocs.io/en/stable/getting_started/#4-login-using-the-cli
#   ---
#   The initial password is autogenerated to be the pod name of the Argo CD API server. This can be retrieved with the command:
#   kubectl get pods -n argocd -l app.kubernetes.io/name=argocd-server -o name | cut -d'/' -f 2
#   ---
# Use the following var to set admin password
# argocd_admin_password: "password"

# Utility for parsing argocd responses
yq_version: v4.40.5

# The plugin manager for kubectl
krew_enabled: true
krew_version: v0.4.4
krew_root_dir: "/usr/local/krew"

kustomize_enabled: true
kustomize_version: v5.3.0

enable_network_policy: true

# MetalLB deployment
metallb_enabled: true
metallb_speaker_enabled: "{{ metallb_enabled }}"
metallb_version: v0.13.11

app_template_version: 3.0.2

elastic_chart_version: 2.10.0
mysql_version: 8.0.35
prometheus_version: 2.47.0
prometheus_operator_version: v0.75.2
kube_prometheus_stack_chart_version: 61.7.2
vault_chart_version: 0.25.0
keycloak_version: 25.0.2

grafana_dashboards:
  - folder_name: Ceph
    dashboards:
      - 5336 # CephOSD
      - 5342 # Ceph Pools
      - 2842 # Ceph Cluster
  - folder_name: Database
    dashboards:
      - 763 # Redis
      - 12776 # Redis (from datasource)
  - folder_name: DNS
    dashboards:
      - 12539 # CoreDNS
      - 14981 # Another CoreDNS?
      - 15038 # External DNS
  - folder_name: Ingress
    dashboards:
      - 9614 # NGINX Ingress
      # - 4475 # Traefik
