---
storage:
  namespaces:
    - services
    - media
    - downloads
  volumes:
    - name: files
      path: /share/Files
      size: &share 5.5Ti
    - name: books
      path: /share/Books
      size: *share
    - name: pictures
      path: /share/Pictures
      size: *share
    - name: movies
      path: /videos/Movies
      size: &videos 7.5Ti
    - name: tv-shows
      path: "/videos/TV Shows"
      size: *videos
    - name: audio
      path: /share/Audio
      size: *share
    - name: downloads
      path: /share/Downloads
      size: *share
    - name: music
      path: /share/Music
      size: *share
